### ISSUE TITLE
Movie list not completely visible multiple servers

### ISSUE THREAD

**Issue by F33db3ck** [fxsth/pledo#13]
Nice work building this.

When logging into plex at the Pledo login page syncing movies and series from multiple servers.
However movies displayed from multiple resources is incomplete. One source has 1900 movies (verified with Plex) but only about 40 are showing.

Hope you can fix this.

Kind regards

**Comment by fxsth** [comment]
Hi, 
there might be a connection issue which has an effect on syncing. Next release should probably fix this.
Which platform do you use? Windows/Linux (Docker)? x86 or ARM?

**Comment by F33db3ck** [comment]
Hi fxsth,

Thanks for the quick response.

I am using docker on my Windows 11 x64 desktop, latest ghcr.io/fxsth/pledo release

**Comment by fxsth** [comment]
Hi, new release v1.2.0 is published now. I hope it fixes your problem.
You can update to latest version by `docker-compose pull` if you use docker-compose.

**Comment by F33db3ck** [comment]
Thanks for the effort, unfortunately it's still not working.

Kind regards.

**Comment by fxsth** [comment]
Actually I dont have a clue, what could go wrong while searching for movies. It seemed to be very straight forward.
Maybe I'll get an idea, when I look into the code. Unfortunately there is not that much of detailed logging in the app, next release should go more into detail - it could get at least get some library stats about total number of movies / episodes.

**Comment by fxsth** [comment]
Apparently there was an issue on metadata sync requesting too much metadata at once. This should be fixed by now.

**Comment by F33db3ck** [comment]
Better than before.

One server with movies in Plex, 188 now visible in Pledo.
Other server with 2639 movie in Plex, 258 visible in Pledo.

Got a lot of the beneath error messages, are the helpfull?

An error occured while retrieving metadata batch: Request returned 0 items in this batch. Sync will continue though.

**Comment by F33db3ck** [comment]
Series are still complete, no problem with them.

**Comment by alafad** [comment]
Same problem for me, my Movie Library has 27000 movies listed in Plexripper but only about 10000 in Pledo.

I've retried the sync multiple times, but the issue still exists..

**Comment by alafad** [comment]
I've tried a rollback, the latest working version with all media is v1.0.2 for me.

**Comment by alafad** [comment]
Sorry for the missinformations, v1.0.2 does have more than the latest release, but there are bunch of media missing even after resync.

**Comment by fxsth** [comment]
Seems to be a huge problem. I´m working on it!
@panzli What about the other log messages with "does not contain any file" - Are the log messages correct or is this another issue?

**Comment by fxsth** [comment]
I pushed an experimental fix to `ghcr.io/fxsth/pledo:master` ("master", not "latest" tag).
Do you mind do try this version? 
If you're using the docker compose snippet from Readme, you have to change the tag from 'latest' to 'master', execute `docker-compose pull` and start it again by `docker-compose up -d`.

**Comment by F33db3ck** [comment]
Thanks for the effort, but no, unfortunately.

![image](https://github.com/fxsth/pledo/assets/3051934/470a629f-323d-4d39-b144-2a07bbf63695)

1st library, about 500 movies visible (real total, about 2000)
2nd library, about 900 movies visible (real total, about 2700)

**Comment by alafad** [comment]
I can reproduce this, 

latest release: 7000 movies
maser release: 8000 movies
real media: 27000 movies


The sync isn't logged in the docker logs since a few versions and i could'nt find any logfile after a quick search.

Could you provide me please a location for the logs?

**Comment by fxsth** [comment]
Anyone owning such a movie library that cannot be synced completely and is willing to send me an invitation link? fxsth[at]pm.me
Otherwise I’m not able to reproduce this issue and I can only keep trying „blindfolded“ fix attempts.

@alafad you should see the logs by executing `docker logs <container name>`

**Comment by fxsth** [comment]
@panzli Yes, thank you! I will try this out.

**Comment by fxsth** [comment]
After all, there is a new fix on `ghcr.io/fxsth/pledo:master`. The issue is related to plex api requests returning collections and it didn't sync its children.
When I fixed it, there were so many items in the database that the frontend was overloaded. So I added pagination and a search. Feel free to test it, I'll release it to `latest`-tag the next days.

**Comment by F33db3ck** [comment]
And done. ;-)

You're the best.

Thank you.

![image](https://github.com/fxsth/pledo/assets/3051934/08433f42-7bee-467f-ba53-f8cc5d6d013d)
